name: bpref
channels:
  - defaults
dependencies:
  - python=3.8
  - pytorch=1.12.1
  - cudatoolkit=11.3
  - absl-py
  - pyparsing
  - pip
  - pip:
    - termcolor
     - git+https://github.com/deepmind/dm_control.git@d1fe1d14fb229d3ad784e40d8c54491d30e1f08a
    - tb-nightly
    - imageio
    - imageio-ffmpeg
    - git+https://github.com/facebookresearch/hydra@0.11_branch
    - matplotlib
    - glfw==1.11.2
    - scikit-image
